name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web          # onde estão cypress/ e package.json dos testes
          start: npm run dev              # comando pra subir a aplicação antes dos testes
          wait-on: 'http://localhost:3000' # aguarda a app estar pronta (ajuste a porta se necessário)

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: web/cypress/videos
          if-no-files-found: ignore